
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: <%= Settings.database["user_name"] %>
  password: <%= Settings.database["password"] %>
  host: localhost

development:
  <<: *default
  database: free-wifi-cafe_development

test:
  <<: *default
  database: free-wifi-cafe_test


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port:     <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
